### PR TITLE
Sprites and naming

### PR DESCRIPTION
**Pull request by theZivkovic**
- Sprites added for additional two switch positions. Names are changed for pipe sprites. For example, pipe_bottom_left means that it goes from bottom to left side (just to avoid confusion)
- 'Pipe' prefab renamed to 'SwitchPrefab'
- Changed the sprite for the root switch
- Adobe Illustrator files are moved to a separate folder inside Sprites folder

### CODE REVIEW

**Comment by MarkoKrstic90** [comment]
Nice root switch. New pipes naming convention are also clearer. I just have a question regarding pipe_left_up, pipe_left_down, pipe_right_up, pipe_right_down. Do we need those pipes too? Besides that, everything seems fine and can go to master branch.

**Comment by theZivkovic** [comment]
Very unusual that we're discussing this in English :) I believe that we already have those pipes. For example, pipe_left_top has the same drawing as pipe_top_left. Correct me if I'm wrong

**Comment by MarkoKrstic90** [comment]
Who knows, maybe one day we will get some foreign contributors. We work on a really amazing game. 

My mistake, you are right. Should I merge it and close or wait for other reviews?

**Comment by theZivkovic** [comment]
YEAH! Merge merge merge

**Pull request merged**
